name: testsuite
on: [push, pull_request]
jobs:
  testsuite-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: make tests
      - run: make cpp_tests
  testsuite-clang11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install clang-11
      - run: make tests
      - run: make cpp_tests
  testsuite-clang12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install clang-12
      - run: make tests
      - run: make cpp_tests
  testsuite-clang12-perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install clang-12
      - run: make malloc_cmp_test
  testsuite-clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install clang clang-format-12
      - run: make format-ci
  testsuite-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make tests CC=gcc CXX=g++
      - run: make cpp_tests CC=gcc CXX=g++
  testsuite-musl:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - run: apk update && apk add build-base bash musl-dev linux-headers
      - run: make tests CC=gcc CXX=g++
      - run: make cpp_tests CC=gcc CXX=g++



